/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;



import javax.swing.JOptionPane;
import model.Detalhes;

/**
 *
 * @author larak
 */
public class DetalhesConsulta extends javax.swing.JFrame {

   //
   
    public DetalhesConsulta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblDetalhes = new javax.swing.JLabel();
        checkConsultaRealizada = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtObservacao = new javax.swing.JTextArea();
        btnFinalizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblDetalhes.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblDetalhes.setText("Detalhes da Consulta");

        checkConsultaRealizada.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        checkConsultaRealizada.setText("Consulta Realizada");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Receita e observações:");

        txtObservacao.setColumns(20);
        txtObservacao.setRows(5);
        jScrollPane1.setViewportView(txtObservacao);

        btnFinalizar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnFinalizar.setText("Finalizar");
        btnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFinalizar)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(checkConsultaRealizada)
                    .addComponent(lblDetalhes))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(lblDetalhes)
                .addGap(30, 30, 30)
                .addComponent(checkConsultaRealizada)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnFinalizar)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarActionPerformed
       //chama o método para finalizar, vindo a posicao da tela principal
       int posicao = TelaPrincipal.telaPrincipal.pegarPosicao();
       if(!getDetalhes().getReceitaEObservacao().equals("")){
       
       if(checkConsultaRealizada.isSelected()){
              
       TelaPrincipal.telaPrincipal.atualizarJaRealizada(consultaRealizada(), posicao);
       TelaPrincipal.telaPrincipal.guardarObs(getDetalhes().getReceitaEObservacao(), posicao);
       this.dispose();
       }else{
           TelaPrincipal.telaPrincipal.guardarObs(getDetalhes().getReceitaEObservacao(), posicao);
           this.dispose();
       }
       }else{
           JOptionPane.showMessageDialog(rootPane, "Observação não pode estar vazio ");

       }  
    }//GEN-LAST:event_btnFinalizarActionPerformed
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetalhesConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetalhesConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetalhesConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetalhesConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DetalhesConsulta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JCheckBox checkConsultaRealizada;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDetalhes;
    private javax.swing.JTextArea txtObservacao;
    // End of variables declaration//GEN-END:variables

public Detalhes getDetalhes(){
    Detalhes detalhes = new Detalhes ();
    
    detalhes.setConsultaRealizada("Não");
    detalhes.setConsultaSelecionada(1);
    detalhes.setReceitaEObservacao(txtObservacao.getText());
    
    
    
    
    
    
    return detalhes;
}
    public String consultaRealizada(){
        String resposta;
        if(getDetalhes().getConsultaRealizada().equals("")){
            resposta = "Não";
            
        }else{
            resposta = "jaRealizada";
        }
        
        return resposta;
    }
    public void mostrarObs(String mesagem){
        txtObservacao.setText(mesagem);
       }
    public void checkConsultaOff(){
        
        btnFinalizar.setVisible(false);
        checkConsultaRealizada.setSelected(true);
        checkConsultaRealizada.setEnabled(false);
        
    }
    public void checkConsultaOn(){
        
        btnFinalizar.setVisible(true);
        checkConsultaRealizada.setSelected(false);
        checkConsultaRealizada.setEnabled(true);
        
    }
    

    






}
